### ISSUE TITLE
Project does not compile when SwiftSimctl added through CocoaPods

### ISSUE THREAD

**Issue by stolyarenkokswing** [ctreffs/SwiftSimctl#6]
Issue founded and described in SwiftSimctlExamplePod, but related to SwiftSimctl pod, that why I write there also and attach the link to issue description:

https://github.com/ctreffs/SwiftSimctlExamplePod/issues/1

**Comment by ctreffs** [comment]
Hi @stolyarenkokswing ,
thanks for reporting this, I'm on it - the fix is clear.
The fix will be provided with release 0.2.1 (#7)

**Comment by ctreffs** [comment]
Podspecs are released

- https://github.com/CocoaPods/Specs/commit/90c1f1b6a2297f60077748b1698ae145fea9dec8
- https://github.com/CocoaPods/Specs/commit/3e8206eccf970eef06692892bb28e10a3c7a7df6
- https://github.com/CocoaPods/Specs/commit/b74e52e549c8881a76d94d4562d0acd73852b7e8

problem should be fixed now.
I'll close the ticket.

Let me know if this fixes your issue.
